[package]
name = "empress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
dbus = "*"
dbus-tree = "*"
glob = "*"

[build-dependencies]
bindgen = "*"
